"""create rules table

Revision ID: 590e0ae55fc0
Revises: 
Create Date: 2026-05-02 20:05:14.376414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '590e0ae55fc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigma_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('stable', 'test', 'experimental', 'deprecated', 'unsupported', name='sigma_status'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('modified', sa.Date(), nullable=True),
    sa.Column('references', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('falsepositives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('level', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='sigma_level'), nullable=True),
    sa.Column('logsource_category', sa.String(length=128), nullable=True),
    sa.Column('logsource_product', sa.String(length=128), nullable=True),
    sa.Column('logsource_service', sa.String(length=128), nullable=True),
    sa.Column('logsource_definition', sa.Text(), nullable=True),
    sa.Column('detection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_rule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sigma_rules')
    # ### end Alembic commands ###
